universe = vanilla
executable = run_pytorch_gpu.sh
arguments = 

log = logs/pytorch_gpu_$(Cluster).log
output = logs/pytorch_gpu_$(Cluster)_$(Process).out
error = logs/pytorch_gpu_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = EVE.tar.gz,pytorch_gpu_test_cuda.py,http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/xaa_pytorch_gpu_tar_gz,http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/xab_pytorch_gpu_tar_gz,http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/xac_pytorch_gpu_tar_gz

requirements = (OpSysMajorVer >= 7)

request_cpus = 1
request_memory = 5GB
request_disk = 10GB


if defined NOGPU
  request_cpus = 1
else
  request_gpus = 1
  +WantGPULab = true
  +GPUJobLength = "short" 
  require_gpus = (Capability > 5.0)
endif

+WantFlocking = true
+WantGlideIn = true

queue 1 
