universe = vanilla

executable = run_hmmer.sh
arguments = jojoba.fasta SMALL

log = output/hmmer_full.log
output = output/hmmer_full.out
error = output/hmmer_full.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = hmmer.tar.gz, jojoba.fasta

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 1
request_memory = 1GB
request_disk = 100MB

queue
