universe = vanilla

executable = run_sfetch.sh
arguments = hmmer_MAACR_scored_seqs.ids.txt FULL

log = output/sfetch_full.log
output = output/sfetch_full.out
error = output/sfetch_full.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = hmmer.tar.gz, hmmer_MAACR_scored_seqs.ids.txt

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 2
request_memory = 50GB
request_disk = 150GB

queue
