universe = vanilla

executable = run_hmmer.sh
arguments = test_query.fasta SMALL

log = output/test_hmmer_small.log
output = output/test_hmmer_small.out
error = output/test_hmmer_small.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = hmmer.tar.gz, test_query.fasta

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 1
request_memory = 1GB
request_disk = 100MB

queue
