universe = vanilla

log = logs/ligand_dock_$(Cluster).log
error = logs/ligand_dock_$(Cluster)_$(Process).err 
output = logs/ligand_dock_$(Cluster)_$(Process).out

requirements = OpSysMajorVer >= 7 && \
               has_avx == true && \
               has_avx2 == true && \
               Machine =!= LastRemoteHost && \
               (GlideIn_Site != "VU-AUGIE")


# run outside CHTC only
# && (Poolname =!= "CHTC")

executable = ligand_dock.sh
arguments = $(Process) $(START_STRUCT) $(variant) $(NSTRUCT)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = inputs.tar.gz,\
    create_variant_xml.sh, \
    osdf:///chtc/staging/dcosta2/2021_38/rosetta_scripts.static.linuxgccrelease,\
    osdf:///chtc/staging/dcosta2/2021_38/db.tar.gz.partaa,\
    osdf:///chtc/staging/dcosta2/2021_38/db.tar.gz.partab

#    osdf:///chtc/staging/dcosta2/2021_38/relax.static.linuxgccrelease,\

request_cpus = 1
#request_memory = 4GB
request_memory = 10GB
# need more disk space as we are running 5000 structures
request_disk = 10GB

max_retries = 5
# exit code 11 is when our output is smaller than 10kB
on_exit_remove = (ExitBySignal == False) && (ExitCode != 11)



+WantFlocking = true
+WantGlideIn = true

# Tell HTCondor to run some instances of our job:
queue variant from $(VARIANT_LIST_FILE)

