universe = vanilla

log = logs/ligand_dock_$(Cluster).log
error = logs/ligand_dock_$(Cluster)_$(Process).err 
output = logs/ligand_dock_$(Cluster)_$(Process).out

requirements = (OpSysMajorVer == 7) && (has_avx == true)

executable = ligand_dock.sh
arguments = $(Process) options.txt 10

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = options.txt,\
    http://proxy.chtc.wisc.edu/SQUID/dcosta2/3_10/rosetta_scripts.static.linuxgccrelease,\
    http://proxy.chtc.wisc.edu/SQUID/dcosta2/3_10/db.tar.bz2.parta,\
    http://proxy.chtc.wisc.edu/SQUID/dcosta2/3_10/db.tar.bz2.partb


request_cpus = 1
request_memory = 4GB
request_disk = 5GB

# Tell HTCondor to run some instances of our job:
queue 1

