universe = vanilla

# the script that will be run when the job starts
executable = run.sh $(Cluster)_$(cProcess)

# include the cluster id and process id that are set at runtime
log = run_output/condor_logs/job_$(Cluster)_$(cProcess).log
error = run_output/condor_logs/job_$(Cluster)_$(cProcess).err
output = run_output/condor_logs/job_$(Cluster)_$(cProcess).out

# these files get transferred from the submit node to the server on which the program is executing
# transfer over code, data, and arguments
#transfer_input_files = run.sh, code.tar.gz, args/$(cProcess).txt, {transfer_input_files}
transfer_input_files = run.sh, code.tar.gz, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/esm/hub.tar.gz, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.aa, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ab, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ac, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ad


should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#transfer_output_files = $ENV(LOG_DIR_BASE)
preserve_relative_paths = true

requirements = (OpSysMajorVer == 7 || OpSysMajorVer == 8)

if ! defined DISABLE_GPU
# condor_submit was run from the command line like 
# condor_submit DISABLE_GPU=1 esm.sub 
  request_gpus = 1
  # We require a machine with a modern version of the CUDA driver
  #Requirements = (Target.CUDADriverVersion >= 10.1) && (Target.CUDACapability >= 5) 
  #require_gpus = (DriverVersion >= 11.1)

  +WantGPULab = true
  +GPUJobLength = "short"
  +is_resumable = true
  request_cpus = 4
else
  request_cpus = 12
endif


request_memory = 16GB
request_disk = 20GB


+WantFlocking = true
+is_resumable = true

requirements = TARGET.Machine =!= "vetsigian0000.chtc.wisc.edu"

cProcess = 1

queue 

