universe = vanilla

# the script that will be run when the job starts
executable = run.sh

# include the cluster id and process id that are set at runtime
log = run_output/condor_logs/job_$(Cluster)_$(cProcess).log
error = run_output/condor_logs/job_$(Cluster)_$(cProcess).err
output = run_output/condor_logs/job_$(Cluster)_$(cProcess).out

# these files get transferred from the submit node to the server on which the program is executing
# transfer over code, data, and arguments
#transfer_input_files = run.sh, code.tar.gz, args/$(cProcess).txt, {transfer_input_files}
transfer_input_files = run.sh, code.tar.gz, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.aa, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ab, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ac, \
  http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/rtl.tar.gz.ad


should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#transfer_output_files = $ENV(LOG_DIR_BASE)
preserve_relative_paths = true

requirements = (OpSysMajorVer == 7 || OpSysMajorVer == 8)


request_cpus = 4
request_memory = 16GB
request_disk = 20GB


+WantFlocking = true
+is_resumable = true


cProcess = 1

queue 

