universe = vanilla

# the script that will be run when the job starts
executable = run.sh

# include the cluster id and process id that are set at runtime
log = run_output/condor_logs/job_$(Cluster)_$(cProcess).log
error = run_output/condor_logs/job_$(Cluster)_$(cProcess).err
output = run_output/condor_logs/job_$(Cluster)_$(cProcess).out

# these files get transferred from the submit node to the server on which the program is executing
# transfer over code, data, and arguments
#transfer_input_files = run.sh, code.tar.gz, args/$(cProcess).txt, {transfer_input_files}

include: ./add_transfer_output_files.sh rtl_2022-06-07_20-53-56.txt |
transfer_input_files = run.sh, {transfer_input_files}

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#transfer_output_files = $ENV(LOG_DIR_BASE)
preserve_relative_paths = true

requirements = (OpSysMajorVer == 7 || OpSysMajorVer == 8)


request_cpus = 1
request_memory = 1GB
request_disk = 5GB


+WantFlocking = true
+is_resumable = true


cProcess = 1

queue 

