universe = vanilla

executable = run_alphafold.sh
arguments = target.fasta

log = logs/alphafold.log.$(cluster)
output = logs/alphafold.out.$(cluster)
error = logs/alphafold.err.$(cluster)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run_alphafold.sh, run_alphafold.py, target.fasta, hmmer_output.tar.gz, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_aa, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ab , http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ac 


request_memory = 16GB
request_disk = 20GB
request_cpus = 1

if ! defined DISABLE_GPU
# condor_submit was run from the command line like 
# condor_submit DISABLE_GPU=1 alphafold.sub 
  request_gpus = 1
  # We require a machine with a modern version of the CUDA driver
  #Requirements = (Target.CUDADriverVersion >= 10.1) && (Target.CUDACapability >= 5) 
  #require_gpus = (DriverVersion >= 11.1)

  +WantGPULab = true
  +GPUJobLength = "short"
  +is_resumable = true
endif

queue
