universe = vanilla

executable = run_alphafold.sh
arguments = target.fasta

log = logs/alphafold.log
output = logs/alphafold.out
error = logs/alphafold.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

#transfer_input_files = run_alphafold.sh, target.fasta, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_aa, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ab, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ac, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ad
transfer_input_files = run_alphafold.sh, target.fasta, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_aa, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ab 
request_memory = 1GB
request_disk = 20GB


queue
