universe = vanilla

executable = run_alphafold.sh
arguments = target.fasta

log = logs/alphafold.log
output = logs/alphafold.out
error = logs/alphafold.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run_alphafold.sh, run_alphafold.py, openmm.patch, target.fasta, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_aa, http://proxy.chtc.wisc.edu/SQUID/dcosta2/py39/alphafold_conda_tar_gz_ab 

request_memory = 5GB
request_disk = 20GB
request_cpus = 1

request_gpus = 1
+WantGPULab = true
+GPUJobLength = "short"
+is_resumable = true

#require_gpus = (DriverVersion >= 11.1)

queue
