universe = vanilla

executable = run_hmmer.sh
BASENAME_DB_GZ=$BASENAME(DB_GZ)
arguments = target.fasta $(BASENAME_DB_GZ) $(DB_Z_VAL) 

log = logs/test_hmmer_small.log
output = logs/test_hmmer_small.out
error = logs/test_hmmer_small.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run_hmmer.sh, ../hmmer/hmmer.tar.gz, target.fasta, http://proxy.chtc.wisc.edu/SQUID/dcosta2/alphafold_db/$(BASENAME_DB_GZ)

request_cpus = 1
request_memory = 1GB
request_disk = 2GB

DB_Z_VAL=135301051
queue DB_GZ matching files /squid/dcosta2/alphafold_db/uniref90_2021_03.fasta.*.gz

DB_Z_VAL=65984053
queue DB_GZ matching files /squid/dcosta2/alphafold_db/bfd-first_non_consensus_sequences.fasta.*.gz

DB_Z_VAL=304820129
queue DB_GZ matching files /squid/dcosta2/alphafold_db/mgy_clusters_2019_05.fasta.*.gz



