universe = vanilla

executable = run_hmmer.sh
arguments = target.fasta uniref90_2021_03.fasta.1.gz 135301051

log = logs/test_hmmer_small.log
output = logs/test_hmmer_small.out
error = logs/test_hmmer_small.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run_hmmer.sh, ../hmmer/hmmer.tar.gz, target.fasta, http://proxy.chtc.wisc.edu/SQUID/dcosta2/alphafold_db/uniref90_2021_03.fasta.1.gz

request_cpus = 1
request_memory = 1GB
request_disk = 2GB

queue

